import numpy as np
import tensorflow as tf
#1*3  3*2   只能相乘，但是不能点乘，一维向量不能扩展至和多维向量一致，多维向量不能扩展
a=np.array([[1,2,3]])
b=np.array([[1,2],[2,3],[3,4]])
print("dot",np.dot(a,b))
# print("*", a*b)
#1*2  3*2  只能点乘，不能相乘
a=np.array([[1,2]])
b=np.array([[1,2],[2,3],[3,4]])
print("multiply",np.multiply(a,b))
print("*", a*b)
#都是一维  相乘只要满足行列对应相等即可，点乘，两个都是一维向量，都能扩展
a=np.array([[1,2,3]])
b=np.array([[1],[2],[3]])
print(np.dot(a,b))
print(np.multiply(a,b))
#######################################################################
a=tf.constant([[1,2,3]])
b=tf.constant([[1,2],[2,3],[3,4]])
c=tf.matmul(a,b)
sess=tf.Session()
print("matmul",sess.run(c))
a=tf.constant([[1,2]])
b=tf.constant([[1,2],[2,3],[3,4]])
c=tf.multiply(a,b)
print("multiply",sess.run(c))
a=tf.constant([[1,2,3]])
b=tf.constant([[1],[2],[3]])
c=tf.matmul(a,b)
cc=tf.multiply(a,b)
sess=tf.Session()
print(sess.run(c))
print(sess.run(cc))
sess.close()
