model:
  class_path: anomalib.models.Ganomaly
  init_args:
    batch_size: 32
    n_features: 64
    latent_vec_size: 100
    extra_layers: 0
    add_final_conv_layer: true
    wadv: 1
    wcon: 50
    wenc: 1
    lr: 0.0002
    beta1: 0.5
    beta2: 0.999

task: CLASSIFICATION

trainer:
  max_epochs: 100
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 3
        monitor: image_AUROC
        mode: max
