model:
  class_path: anomalib.models.Padim
  init_args:
    layers:
      - layer1
      - layer2
      - layer3
    backbone: resnet18
    pre_trained: true
    n_features: null

metrics:
  pixel: AUROC
